/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.clientes.vista;

import co.unicauca.clientes.modelo.ClientesDB;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author WINDOWS10
 */
public class GUIEstadisticaPorSexoGrafica extends javax.swing.JFrame implements Observer{

    /**
     * Constructor
     *
     * @param h horizontal position
     * @param v vertical position
     */
    public GUIEstadisticaPorSexoGrafica(int h, int v) {
        initComponents();
        txtHombres.setVisible(false);
        txtMujeres.setVisible(false);
        barHombres.setVisible(false);
        barMujeres.setVisible(false);
        lblHombres.setVisible(false);
        lblMujeres.setVisible(false);
        
        setSize(400, 350);
        setLocation(h, v);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        barHombres = new rojerusan.componentes.RSProgressBar();
        barMujeres = new rojerusan.componentes.RSProgressBar();
        lblHombres = new javax.swing.JLabel();
        txtMujeres = new javax.swing.JTextField();
        lblMujeres = new javax.swing.JLabel();
        txtHombres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        barHombres.setForeground(new java.awt.Color(102, 0, 102));
        barHombres.setValue(0);
        barHombres.setOrientacion(rojerusan.componentes.RSProgressBar.ORIENTACION.VERTICAL);
        barHombres.setStringPainted(false);

        barMujeres.setForeground(new java.awt.Color(102, 0, 102));
        barMujeres.setValue(0);
        barMujeres.setEnabled(false);
        barMujeres.setOrientacion(rojerusan.componentes.RSProgressBar.ORIENTACION.VERTICAL);
        barMujeres.setStringPainted(false);

        lblHombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHombres.setText("Hombres");

        txtMujeres.setEditable(false);
        txtMujeres.setBackground(new java.awt.Color(255, 255, 255));
        txtMujeres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMujeres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMujeres.setSelectionColor(new java.awt.Color(255, 255, 255));

        lblMujeres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMujeres.setText("Mujeres");

        txtHombres.setEditable(false);
        txtHombres.setBackground(new java.awt.Color(255, 255, 255));
        txtHombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHombres.setSelectionColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblHombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHombres, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(barHombres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMujeres)
                            .addComponent(barMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHombres, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barHombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHombres)
                    .addComponent(lblMujeres))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barMujeres.getAccessibleContext().setAccessibleParent(barMujeres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEstadisticaPorSexoGrafica(400, 200).setVisible(true);
            }
        });
    }

    @Override
    public void update(Observable obs, Object obj) {
        ClientesDB cliDB = (ClientesDB) obs;
        this.setTitle("Profesion: " + cliDB.getProfesion());
        graficar(cliDB);
    }

    private void graficar(ClientesDB cliente) {
        
        txtHombres.setVisible(true);
        txtMujeres.setVisible(true);
        barHombres.setVisible(true);
        barMujeres.setVisible(true);
        lblHombres.setVisible(true);
        lblMujeres.setVisible(true);
        
        float pM = cliente.porcentajeMujeres();
        float p1 = (float) (Math.round(pM*100) / 100d);
        
        float pH = cliente.porcentajeHombres();
        float p2 = (float) (Math.round(pH*100) / 100d);
        
        this.barMujeres.setValue((int)cliente.porcentajeMujeres());
        this.barHombres.setValue((int)cliente.porcentajeHombres());
        
        txtHombres.setText(p2 + " %");
        txtMujeres.setText(p1 + " %");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private rojerusan.componentes.RSProgressBar barHombres;
    private rojerusan.componentes.RSProgressBar barMujeres;
    private javax.swing.JLabel lblHombres;
    private javax.swing.JLabel lblMujeres;
    private javax.swing.JTextField txtHombres;
    private javax.swing.JTextField txtMujeres;
    // End of variables declaration//GEN-END:variables
}
